name: Moodle Plugin CI

on: [push, pull_request, workflow_dispatch]

jobs:
  selftest:
    name: CI test (make validate)
    runs-on: ubuntu-20.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup PHP 7.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.3

    - name: Initialise
      run: make init

    - name: Validate
      run: make validate

  citest:
    name: CI test
    needs: selftest
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        # Health check to wait for postgres to start.
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      oracle:
        image: moodlehq/moodle-db-oracle-r2
        env:
          ORACLE_DISABLE_ASYNCH_IO: true
        ports:
          - 1521:1521

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '7.4'
            moodle-branch: 'master'
            database: 'pgsql'
            extensions: 'mbstring, zip, gd, xmlrpc, soap, pgsql'
          - php: '7.4'
            moodle-branch: 'MOODLE_311_STABLE'
            database: 'oci'
            extensions: 'mbstring, zip, gd, xmlrpc, soap, oci8'
            ciinstallparams: '--db-user moodle --db-pass "m@0dl3ing" --db-name XE'
          - php: '7.4'
            moodle-branch: 'MOODLE_310_STABLE'
            database: 'pgsql'
            extensions: 'mbstring, zip, gd, xmlrpc, soap, pgsql'
          - php: '7.4'
            moodle-branch: 'MOODLE_39_STABLE'
            database: 'oci'
            extensions: 'mbstring, zip, gd, xmlrpc, soap, oci8'
            ciinstallparams: '--db-user moodle --db-pass "m@0dl3ing" --db-name XE'
          - php: '7.4'
            moodle-branch: 'MOODLE_38_STABLE'
            database: 'pgsql'
            extensions: 'mbstring, zip, gd, xmlrpc, soap, pgsql'
          - php: '7.2'
            moodle-branch: 'MOODLE_35_STABLE'
            database: 'oci'
            extensions: 'mbstring, zip, gd, xmlrpc, soap, oci8'
            ciinstallparams: '--db-user moodle --db-pass "m@0dl3ing" --db-name XE'
          - php: '7.0'
            moodle-branch: 'MOODLE_35_STABLE'
            database: 'pgsql'
            extensions: 'mbstring, zip, gd, xmlrpc, soap, pgsql'

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Setup PHP ${{ matrix.php }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: ${{ matrix.extensions }}
        coverage: none

    - name: Initialise moodle-plugin-ci
      run: |
        make init
        cp -R tests/Fixture/moodle-local_ci ../moodle-local_ci
        echo $(cd bin; pwd) >> $GITHUB_PATH
        echo $(cd vendor/bin; pwd) >> $GITHUB_PATH
        echo "CI_BUILD_DIR="$(cd ../moodle-local_ci; pwd) >> $GITHUB_ENV
        # PHPUnit depends on en_AU.UTF-8 locale
        sudo locale-gen en_AU.UTF-8
        # Define NVM_DIR pointing to nvm installation.
        echo "NVM_DIR=$HOME/.nvm" >> $GITHUB_ENV

    - name: Install moodle-plugin-ci
      run: moodle-plugin-ci install -vvv ${{ matrix.ciinstallparams }}
      env:
        DB: ${{ matrix.database }}
        MOODLE_BRANCH: ${{ matrix.moodle-branch }}
        IGNORE_PATHS: 'ignore'
        IGNORE_NAMES: 'ignore_name.php'
        MUSTACHE_IGNORE_NAMES: 'broken.mustache'

    - name: Run Integration tests
      env:
        MOODLE_BRANCH: ${{ matrix.moodle-branch }}
      run: |
        moodle-plugin-ci phplint
        moodle-plugin-ci phpcpd
        moodle-plugin-ci phpmd
        moodle-plugin-ci codechecker
        moodle-plugin-ci validate
        moodle-plugin-ci savepoints
        moodle-plugin-ci mustache
        moodle-plugin-ci grunt ||  [ \
            "$MOODLE_BRANCH" != 'master' -a \
            "$MOODLE_BRANCH" != 'MOODLE_311_STABLE' -a \
            "$MOODLE_BRANCH" != 'MOODLE_310_STABLE' -a \
            "$MOODLE_BRANCH" != 'MOODLE_39_STABLE' ]
        moodle-plugin-ci phpdoc
        moodle-plugin-ci phpunit --verbose --coverage-text
        moodle-plugin-ci behat --profile default
        moodle-plugin-ci behat --profile chrome
